### PR TITLE
Various updates for HLT

### PR DESCRIPTION
**Pull request by tstreble**
This PR adds various features developed originally for HLT.
In particular:
- TauID discriminants added for possible tightening of iso in case Ntuple produced with loose iso
- Added possibility to bypass mass cuts for T&P to run on fakes with larger stats
- Added HLT specific variables
- Updated HLT paths in config files

Please consider for merging

### CODE REVIEW

**Comment by davignon** [comment]
@tstreble 
Thanks. Is this backwards compatible with 2016 MC / data?
Should we add a flag 2016/2017 to be sure the correct HLT paths are picked up?

Cheers,
- Olivier

**Comment by tstreble** [comment]
The default HLT paths are 2017 specific but they can be changed in the files test.py if needed.
As I'm not interested in running performance studies with 2016 HLT paths, the only required update would be to change the HLT path used for filtering SingleMu events.
I've not tested whether the patTriggerUnpacker is backwards compatible.

**Comment by tstreble** [comment]
Runs out of the box on
/store/data/Run2016H/SingleMuon/MINIAOD/PromptReco-v2/000/281/207/00000/C01B8838-6282-E611-9884-02163E01414B.root

**Comment by davignon** [comment]
@tstreble 

Thanks for checking. Nothing else I should be aware of? :-)

Cheers,
- Olivier

**Comment by tstreble** [comment]
Nothing I can think about

**Pull request merged**
